name: project-72-check
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - name: Test code coverage
        if: ${{ github.event_name == 'push' }}
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.TESTCOVERAGE_72}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          coverageCommand: make report
          debug: true
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
